name: Docker Build
inputs:
  docker_tag:
    description: "Commit short SHA"
    required: true
    type: string
  ecr_repository_name:
    required: true
    type: string
  dockerfile_name:
    required: false
    type: string
  build_dir:
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Build docker image
      shell: bash
      env:
        ECR_REPOSITORY: ${{ inputs.ecr_repository_name }}
        IMAGE_TAG: ${{ inputs.docker_tag }}
      run: |
        cd ${{ inputs.build_dir }}
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f ${{ inputs.dockerfile_name }} .
