name: Library - Release and Deploy

on:
  workflow_call:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string
        required: false
      create_release:
        description: "Create a github release for this deployment"
        type: boolean
        required: false
      deploy_review:
        description: "Deploy to review"
        type: boolean
        required: false
      deploy_staging:
        description: "Deploy to staging"
        type: boolean
        required: false
      deploy_production:
        description: "Deploy to production"
        type: boolean
        required: false
    secrets:
      PULUMI_ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID_REVIEW:
        required: true
      AWS_SECRET_ACCESS_KEY_REVIEW:
        required: true
      AWS_ACCESS_KEY_ID_STAGING:
        required: false
      AWS_SECRET_ACCESS_KEY_STAGING:
        required: false
      AWS_ACCESS_KEY_ID_PRODUCTION:
        required: false
      AWS_SECRET_ACCESS_KEY_PRODUCTION:
        required: false
      IAM_SERVER_SSM_ARN_PRODUCTION:
        required: false
      IAM_SERVER_SSM_ARN_STAGING:
        required: false
      ROUTE_53_ZONE_PRODUCTION:
        required: false
      ROUTE_53_ZONE_STAGING:
        required: false

jobs:
  ref:
    name: Load Commit Ref
    runs-on: ubuntu-latest
    steps:
      - id: ref
        shell: bash
        # Default to HEAD of the branch from
        # which this workflow was triggered
        run: |
          echo "refspec=${{ inputs.commit || github.sha }}" >> $GITHUB_OUTPUT
    outputs:
      refspec: ${{ steps.ref.outputs.refspec }}

  test_and_draft_release:
    name: Test and Draft Release
    needs: [ref]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0

      - name: Version
        # https://github.com/marketplace/actions/git-semantic-version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"

      - name: Draft Release
        if: ${{ inputs.create_release }}
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          allowUpdates: true
          token: ${{ secrets.github_token }}
          tag: ${{ steps.version.outputs.version_tag }}
          commit: ${{ needs.ref.outputs.refspec }}
          draft: true

    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}

  docker:
    name: Docker
    needs: [ref, test_and_draft_release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0

      - name: Store Commit SHA
        id: sha
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short ${{ needs.ref.outputs.refspec }})" >> $GITHUB_OUTPUT

      - name: Docker Build
        uses: ./.github/actions/docker_build
        with:
          docker_tag: ${{ steps.sha.outputs.sha_short }}
          ecr_repository_name: scroll-badge-service
          dockerfile_name: Dockerfile
          build_dir: ./
      - name: Docker Push to Review
        uses: ./.github/actions/docker_deploy
        if: ${{ inputs.deploy_review }}
        with:
          docker_tag: ${{ steps.sha.outputs.sha_short }}
          ecr_repository_name: scroll-badge-service
          aws_region: us-west-2
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_REVIEW }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_REVIEW }}
      - name: Docker Push to Staging
        uses: ./.github/actions/docker_deploy
        if: ${{ inputs.deploy_staging }}
        with:
          docker_tag: ${{ steps.sha.outputs.sha_short }}
          ecr_repository_name: scroll-badge-service
          aws_region: us-west-2
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      - name: Docker Push to Production
        uses: ./.github/actions/docker_deploy
        if: ${{ inputs.deploy_production }}
        with:
          docker_tag: ${{ steps.sha.outputs.sha_short }}
          ecr_repository_name: scroll-badge-service
          aws_region: us-west-2
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}

    outputs:
      docker_tag: ${{ steps.sha.outputs.sha_short }}

  deploy_backends:
    name: Deploying AWS Infra
    needs: [ref, docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0
      - name: Prepare to Deploy to AWS
        uses: ./.github/actions/prepare_deploy_to_aws
      - name: Deploy Review
        uses: ./.github/actions/deploy_to_aws
        if: ${{ inputs.deploy_staging }}
        with:
          docker_tag: ${{ needs.docker.outputs.docker_tag }}
          stack_name: gitcoin/scroll-badge-service/review
          aws_region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_REVIEW }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_REVIEW }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ROUTE_53_DOMAIN: ${{ secrets.ROUTE_53_DOMAIN_REVIEW }}
          SCROLL_SECRETS_ARN: ${{ secrets.SCROLL_SECRETS_ARN_REVIEW }}
          VC_SECRETS_ARN: ${{ secrets.VC_SECRETS_ARN_REVIEW }}
      - name: Deploy Staging
        uses: ./.github/actions/deploy_to_aws
        if: ${{ inputs.deploy_staging }}
        with:
          docker_tag: ${{ needs.docker.outputs.docker_tag }}
          stack_name: gitcoin/scroll-badge-service/staging
          aws_region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ROUTE_53_DOMAIN: ${{ secrets.ROUTE_53_DOMAIN_STAGING }}
          SCROLL_SECRETS_ARN: ${{ secrets.SCROLL_SECRETS_ARN_STAGING }}
          VC_SECRETS_ARN: ${{ secrets.VC_SECRETS_ARN_STAGING }}
      - name: Deploy Production
        uses: ./.github/actions/deploy_to_aws
        if: ${{ inputs.deploy_production }}
        with:
          docker_tag: ${{ needs.docker.outputs.docker_tag }}
          stack_name: gitcoin/scroll-badge-service/production
          aws_region: us-west-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ROUTE_53_DOMAIN: ${{ secrets.ROUTE_53_DOMAIN_PRODUCTION }}
          SCROLL_SECRETS_ARN: ${{ secrets.SCROLL_SECRETS_ARN_PRODUCTION }}
          VC_SECRETS_ARN: ${{ secrets.VC_SECRETS_ARN_PRODUCTION }}
  release:
    needs: [deploy_backends, test_and_draft_release, ref]
    if: ${{ inputs.create_release }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.ref.outputs.refspec }}
          fetch-depth: 0

      - name: Release
        # https://github.com/ncipollo/release-action
        uses: ncipollo/release-action@v1
        with:
          omitBodyDuringUpdate: true
          allowUpdates: true
          # token: ${{ secrets.github_token }}
          tag: ${{ needs.test_and_draft_release.outputs.version_tag }}
          commit: ${{ needs.ref.outputs.refspec }}
          draft: false
